[package]
name = "gctree"
version = "0.9.1"
edition = "2021"
description = "A cache-friendly, garbage-collecting tree structure."
license = "MIT"
documentation = "https://docs.rs/gctree"
repository = "https://github.com/jjpe/gctree"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deltoid = "0.11"
deltoid-derive = "0.11"
displaydoc = "0.2"
serde = "1.0"
serde_derive = "1.0"
thiserror = "1.0"
