[package]
name = "gctree"
version = "0.16.0"
edition = "2021"
description = "A library for cache-friendly, graph-like, arena-allocated datastructures."
license = "MIT"
documentation = "https://docs.rs/gctree"
repository = "https://github.com/jjpe/gctree"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deltoid = "0.11.3"
deltoid-derive = "0.11.1"
derive_more = "0.99.17"
displaydoc = "0.2.3"
ioe = "0.5.1"
serde = "1.0.137"
serde_derive = "1.0.137"
thiserror = "1.0.31"

[features]
d2-graphs = []
